# Definitions

---

## Contents

---

1. [Cardinality](#Cardinality)
1. [Condition Number](#Condition-Number)
1. [Rank](#Rank)

## Cardinality

---

> [Wikipedia](https://en.wikipedia.org/wiki/Cardinality)

The cardinality (or size) of a set is a measure of the number of elements in the set.

### Syntax

The cardinality of a set $A$ can be denoted by $|A|$, $n(A)$, $\text{card}(A)$ or $\#A$.

### Example

The set $A = \{1, 1, 2, 3, 5\}$ with $\text{card}(A) = 4$ can be implemented in Python as follows:

In [1]:
# Define the set A.
A = set([1, 1, 2, 3, 5])
print 'A =', A

# Print card(A)
print 'card(A) =', len(A)

A = set([1, 2, 3, 5])
card(A) = 4


## Condition Number

---

> [Wikipedia](https://en.wikipedia.org/wiki/Condition_number)

The condition number of a function with respect to an argument measures how much the output value of the function can change for a small change in the input argument.

The condition number of a matrix can be measured by taking the ratio of its largest and smallest singular values.

### Syntax

The condition number of a matrix $A$ can be denoted by $\kappa(A)$ or cond$(A)$.

### Example

The matrix

$$A = \begin{bmatrix}
  1 & 2 & 1 \\
  -2 & -3 & 1 \\
  3 & 5 & 0
\end{bmatrix}$$

has $\kappa(A) = 2 \times 10^{16}$.

In [5]:
# Define the matrix A.
A = np.array([[1, 2, 1], [-2, -3, 1], [3, 5, 0]])

# Define a function to measure the condition number.
def cond(x):
    
    U, S, V = np.linalg.svd(x)

    return S[0] / S[-1]

# Get cond(A).
print 'cond(A) =', cond(A)

cond(A) = 2.01713939447e+16


## Rank

---

> [Wikipedia](https://en.wikipedia.org/wiki/Rank_(linear_algebra)

The rank is a measure of the number of linearly independent columns (or rows) in a matrix. 

### Syntax

The rank of a matrix $A$ can be denoted by $\text{rank}(A)$. If $A$ has dimensions $m\times n$ then the following inequality must hold:

$$\text{rank}(A)\leq \text{min}(m, n)$$

### Example

The matrix

$$A = \begin{bmatrix}
  1 & 2 & 1 \\
  -2 & -3 & 1 \\
  3 & 5 & 0
\end{bmatrix}$$

has $\text{rank}(A) = 2$ as the first two rows are linearly independent, but the third row is equal to the difference of the first two.


In [24]:
# Define the matrix A.
A = np.array([[1, 2, 1], [-2, -3, 1], [3, 5, 0]])

# Get rank(A).
print 'rank(A) =', np.linalg.matrix_rank(A)

# Test if the rank is less than min(m, n).
print 'rank(A) <= min(m, n):', np.linalg.matrix_rank(A) <= min(*A.shape)

rank(A) = 2
rank(A) <= min(m, n): True


In [25]:
u, s, v = np.linalg.svd(A)
print s
print u

[  7.20971511e+00   1.42126986e+00   3.57422751e-16]
[[-0.30519027 -0.75731471 -0.57735027]
 [ 0.50325864 -0.64295988  0.57735027]
 [-0.80844891 -0.11435482  0.57735027]]


In [32]:
s_new = np.append(s[:2], [0])

print np.dot(u, np.dot(np.diag(s_new), v))

[[  1.00000000e+00   2.00000000e+00   1.00000000e+00]
 [ -2.00000000e+00  -3.00000000e+00   1.00000000e+00]
 [  3.00000000e+00   5.00000000e+00   1.38777878e-16]]


In [33]:
print np.sum(s)

8.63098496882


In [41]:
from functions.matrix import *

B = np.random.randint(-9, 9, 9).reshape(3, 3)

print nuclear_norm(A)
print nuclear_norm(B)

8.63098496882
22.910030107
